AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: News-Digest-Service-Deployment-Descriptor

Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: java11
    MemorySize: 1024
    Timeout: 20
    AutoPublishAlias: !Ref Stage
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    CodeUri: ./application
    Tags:
      Stage: !Ref Stage
      Service: NewsDigest
      Resource: Lambda
    Environment:
      Variables:
        TABLE: !Ref NewsDigestTable
        APPLICATION_ENVIRONMENT: !Ref Stage
        CLOUD_REGION: us-east-1
        MAIN_CLASS: com.tekcapsule.newsdigest.application.NewsDigestApplication
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Resources:

  # Setup API Gateway

  NewsDigestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "news-digest-${Stage}"
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For, Content-Type, Authorization, X-User-Login, X-Channel-Code'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false
      Variables:
        LAMBDA_ALIAS: !Ref Stage

  # Setup DynamoDB Table

  NewsDigestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Stage}Digest"
      AttributeDefinitions:
        - AttributeName: code
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: code
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: categoryGSI
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: category
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

  # Setup Lambda Functions

  CreateNewsDigestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-CreateNewsDigest"
      SnapStart:
        ApplyOn: PublishedVersions
      CodeUri: C:\Users\vishw\news-digest-service\application
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: createFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/create
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  UpdateNewsDigestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-UpdateNewsDigest"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: updateFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/update
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  DisableNewsDigestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-DisableNewsDigest"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: disableFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/disable
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  ApproveNewsDigestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-ApproveNewsDigest"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: approveFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/approve
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  GetNewsDigestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-GetNewsDigest"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/get
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  GetAllNewsDigestsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-NewsDigest-GetAllNewsDigests"
      SnapStart:
        ApplyOn: PublishedVersions
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NewsDigestTable
      Environment:
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: getAllFunction
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: news-digest/getAll
            Method: post
            RestApiId:
              Ref: NewsDigestApi

  # Set Output Variable

Outputs:
  ApiEndpoint:
    Description: "NewsDigest API endpoint."
    Value: !Sub "https://${NewsDigestApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/news-digest"
